### ISSUE TITLE
关于对比学习方法及最后预测特征的使用

### ISSUE THREAD

**Issue by MrShouxingMa** [Ricardo-Ping/DDRec#2]
这里有一个小小的疑惑想请教，既然论文主打硬去噪和软去噪，而且最终进入GCN循环的是公式16产生的结果（整合了硬去噪和软去噪处理后的特征）；为什么在进行对比学习以及最后进行推理时，只是使用公式10和公式4后的结果？
请问作者有对公式16的结果进行实验吗,还是说使用公式公式10和公式4后的结果更好？

祝好！

**Comment by Ricardo-Ping** [comment]
感谢您的关注，公式16是通过软去噪处理之后得到的特征，同时用来硬去噪。我没有对公式16进行过对比学习，您可以尝试一下。直觉上是使用与最终表示更相关的公式10和公式4能够起到对比学习效果。

**Comment by MrShouxingMa** [comment]
我从消融实验观察到软去噪相对其他组件更为重要，这也是合理的；因为你在硬去噪时，使用的用户模态是初始化出来的，再加上后面自己设置阈值进行剪枝；太多人为操作，不像软去噪那样更少的超参和更大程度使用项目多模态数据。
